### PR TITLE
Forwarder

### PR DESCRIPTION
**Pull request by bketelsen**
latest two changes

### CODE REVIEW

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "[skydns] Forwarder (#44)..." ]

> latest two changes
> You can merge this Pull Request by running:
> 
>   git pull https://github.com/miekg/skydns forwarder
> 
> Or you can view, comment on it, or merge it online at:
> 
>   https://github.com/skynetservices/skydns/pull/44
> 
> -- Commit Summary --
> - Implement getArecords different
> - Gofmt it

well, I think you already did 1) and 2) isn't that hard
either :)

grtz Miek

**Comment by bketelsen** [comment]
Now the only thing left to do is document this all.

On Fri, Jan 17, 2014 at 11:37 AM, Miek Gieben notifications@github.comwrote:

> [ Quoting notifications@github.com in "[skydns] Forwarder (#44)..." ]
> 
> > latest two changes
> > You can merge this Pull Request by running:
> > 
> > git pull https://github.com/miekg/skydns forwarder
> > 
> > Or you can view, comment on it, or merge it online at:
> > 
> > https://github.com/skynetservices/skydns/pull/44
> > 
> > -- Commit Summary --
> > - Implement getArecords different
> > - Gofmt it
> 
> well, I think you already did 1) and 2) isn't that hard
> either :)
> 
> grtz Miek
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/skynetservices/skydns/pull/44#issuecomment-32621318
> .

## 

---

Brian Ketelsen
bketelsen <at> gmail <dot> com

**Comment by miekg** [comment]
I'll try to get the readme in some decent shape later this evening (UTC)

**Comment by bketelsen** [comment]
I did the little bit I have time for.

**Comment by crosbymichael** [comment]
I can help with examples this weekend and I plan on making a Go client lib and maybe a cli app for skynds.  If I find any docs that need to be update i'll submit a few PRs.

**Pull request closed without merging**
