### PR TITLE
Add DNSSEC to SkyDNS

### PR DESCRIPTION
**Pull request by miekg**
This adds DNSSEC. Functionality works. But it still need add more testing to check if the spec. is fully followed. If DNSSEC is not enabled the new code isn't used, so this should not trigger any unwanted behaviour in the non-DNSSEC case.

I'm putting this PR out now, because its already large. Future tweaks and more tests will come in subsequent PRs.

### CODE REVIEW

**Comment by bketelsen** [comment]
holy moly!

**Comment by bketelsen** [comment]
this doesn't merge cleanly since I merged the stat PR.  Can you pull latest?

**Comment by crosbymichael** [comment]
I'll try to help and review this soon

**Comment by miekg** [comment]
@bketelsen hmmm, should I then pull master into my dnssec branch? If so, I just did that.

**Comment by crosbymichael** [comment]
@miekg It is usually more advantageous to do a rebase from upstream instead of a merge.  The merge will still work in this case.

**Comment by miekg** [comment]
Local test works, seems like Travis isn't fast enough: some TTLs have the wrong value

**Comment by miekg** [comment]
Woot!

**Pull request merged**
