### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by miekg**
More updates the docs.

Really like your changes, didn't add much

### CODE REVIEW

**Comment by crosbymichael** [comment]
looks good

**Comment by bketelsen** [comment]
Thanks!!

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [skydns] Doc updates (#45)..." ]

> Thanks!!

doing some more work, hitting a snag. In the README.md, section 'Domain Format'

uuid>.<host>.<region>.<version>.<service>.<environment>.skydns.local. 

Where does service come from? Is the Name in the Json? Why the difference?

grtz Miek

**Comment by bketelsen** [comment]
service is "name" in the json.  it's an inconsistency that should be fixed.
 Skydns was originally intended for Skynet services, which each have a very
specific name (AuthService).  That use case isn't clear here, and when
using outside of Skynet service and name are interchangeable.

On Fri, Jan 17, 2014 at 2:38 PM, Miek Gieben notifications@github.comwrote:

> [ Quoting notifications@github.com in "Re: [skydns] Doc updates
> (#45)..." ]
> 
> > Thanks!!
> 
> doing some more work, hitting a snag. In the README.md, section 'Domain
> Format'
> 
> uuid>.<host>.<region>.<version>.<service>.<environment>.skydns.local.
> 
> Where does service come from? Is the Name in the Json? Why the difference?
> 
> grtz Miek
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/skynetservices/skydns/pull/45#issuecomment-32639350
> .

## 

---

Brian Ketelsen
bketelsen <at> gmail <dot> com

**Pull request merged**
