### PR TITLE
Add Callbacks to skydns

### PR DESCRIPTION
**Pull request by miekg**
This enables HTTP Callback for SkyDNS.

Note: the actual callback isn't performed (yet). I wanted early feedback on the idea and/or the implemention.

### CODE REVIEW

**Comment by bketelsen** [comment]
this is failing travis build

**Comment by bketelsen** [comment]
can you fix the conflict and check the broken tests?

**Comment by miekg** [comment]
Ack. Rebasing as we speak. Also made it use Callback instead *Callback as I
suspect that will break raft as it cannot serialize the pointers. Shuffled
some stuff around.

Now onto fixing the test.

**Comment by miekg** [comment]
Ok. Rebased cleanly (I hope) and fixed the test (the bug causing it).

**Pull request merged**
