### PR TITLE
Documentation more Go like

### PR DESCRIPTION
**Pull request by miekg**

### CODE REVIEW

**Comment by bketelsen** [comment]
test is failing - do you know why?

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [skydns] Documentation more Go ..." ]

> test is failing - do you know why?

which one? Because locally all things are working on my laptop.
Also strange that it fails with _this_ patch, as it only touches the
comments...?
Previous pull request (cleanups) also show now failing tests here locally.

Grtz Miek

**Comment by bketelsen** [comment]
don't know why they failed before but passing now, so merged!

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [skydns] Documentation more Go ..." ]

> don't know why they failed before but passing now, so merged!

cool! And thanks for merging my other stuff too!

grtz Miek

**Pull request merged**
