### PR TITLE
Dnsclient infrastructure

### PR DESCRIPTION
**Pull request by miekg**
This adds the infrastructure for querying SkyDNS via the DNS. The actual querying is not implemented (yet!). 
Also lots of documentation (typos and other stuff) fixes all over the map. Fixes in the client to actual list all the actions it supports. Rename get to list in the client.

### CODE REVIEW

**Comment by miekg** [comment]
And now it works. Output is not yet pretty, but it works.

**Comment by bketelsen** [comment]
@crosbymichael - will you look at this and make sure it doesn't break anything you're doing?

**Comment by crosbymichael** [comment]
No problem, looks good so far

**Comment by bketelsen** [comment]
ok @miekg let me know when you want this merged

**Comment by miekg** [comment]
[ Quoting notifications@github.com in "Re: [skydns] Dnsclient infrastructu..." ]

> ok @miekg let me know when you want this merged

Ready to be merged. Heads up: in the output of skydnsctl I crammed the Prio
and Weight in the name (not sure if that is a good idea, but the DNS reply
is very different from the http one).

Grtz Miek

**Pull request merged**
